project_id = "paamalai"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = true

[auth.external.google]
enabled = false

[auth.external.apple]
enabled = false

[functions.generate-devotion]
verify_jwt = true
